[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./"}]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 800
via_ir = false
ffi = true

[fmt]
line_length = 80
number_underscore = "thousands"
multiline_func_header = "all"
sort_imports = true
contract_new_lines = true
override_spacing = false
wrap_comments = true